### ISSUE TITLE
graphical asset

### ISSUE THREAD

**Issue by zhuyuecai** [yixuanzhai/371_Interior_Design#1]
Please search for graphical assets and include the link to source in the comments here.
We will discuss which source to use in the meeting among them.

Thanks

**Comment by yixuanzhai** [comment]
http://tf3dm.com/
site for graphic assets

http://learnopengl.com/#!Model-Loading/Model
model loader, non tested

**Comment by justindupuis** [comment]
Another:
https://3dwarehouse.sketchup.com/?hl=en

**Comment by justindupuis** [comment]
I found the holy grail...
https://www.tinkercad.com/

It's an incredibly simple web-based tool that we can use to draw furniture and other objects and export them as obj files to import into the program. I tested it and it took me about 2 minutes to build a couch...

We can still obviously use prebuilt graphical assets, but we can use this to build things we need that we're having trouble finding.

I'm going to work on using it to model the floor and walls of the room... I'll keep you guys posted :-)
